---
- name: Installing kvm and bridge creation
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
     - name: Run install_vm.sh script
       shell: sh ./../Auto-Deploy-KVM/configure_network.sh
