---
 - hosts: all
   remote_user: centos
   become: true
   vars_files:
    - "../env_variables/host_env_variables"   
   tasks:
     - name: Disable Root Login
       lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin yes'
           line="PermitRootLogin no"
           state=present
           backup=yes
       notify:
        - restart ssh
   handlers:
    - name: restart ssh
      service:
       name=sshd
       state=restarted
