---
 - hosts: all
   remote_user: centos
   become: true
   vars_files:
    - "../env_variables/host_env_variables"   
   tasks:
     - name: Make sure we have a 'wheel' group
       group:
         name: wheel
         state: present

     - name: Allow 'wheel' group to have passwordless sudo
       lineinfile:
         dest: /etc/sudoers
         state: present
         regexp: '^%wheel'
         line: '%wheel ALL=(ALL) NOPASSWD: ALL'
         validate: 'visudo -cf %s'
        
     - name: Add centos user to wheel(sudoers) group
       user: name=centos groups=wheel append=yes state=present createhome=yes

       
     # - name: Set up authorized keys for the root user
    #   authorized_key: user=root key="{{item}}"
    #   with_file:
    #     - /home/{{ host }}/.ssh/id_rsa.pub
   
     - name: Set up authorized keys for the centos user
       authorized_key: user=centos key="{{item}}"
       with_file:
         - /home/{{ host }}/.ssh/id_rsa.pub

         
  
     - name: Enable Root Login
       lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^#PermitRootLogin'
           line="PermitRootLogin yes"
           state=present
           backup=yes
       notify:
        - restart ssh
   handlers:
    - name: restart ssh
      service:
       name=sshd
       state=restarted
